version: "2"
services:
  backend:
    image: node:20-alpine
    container_name: economy-backend
    user: root
    working_dir: /home/node/app
    volumes:
      - ./backend:/home/node/app
    command: "npm start"
    ports:
      - "3000:3000"

  database:
    image: mariadb:10.3.37
    container_name: economy-database
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=economyDB
      - MYSQL_TCP_PORT=3307
    volumes:
      - ./data:/var/lib/mysql
